[package]
name = "buildid"
version = "0.1.0"
edition = "2018"
keywords = ["no_std"]
license = "MPL-2.0"
description = "Examine the currently running executable to get its build-id or LC_UUID"


[target.'cfg(windows)'.dependencies]
object = "0.26"
winapi = "0.3"
