#! /bin/bash
set -x
set -euf -o pipefail

cd "$(dirname "$0")/.."

export BUILD_ID_TEST_EXPECTED="$(hexdump -n 32 -e '4/4 "%08X" 1 ""' /dev/urandom)"

# Force a particular build-id for tests. Assumes gnu-compatible ld
export RUSTFLAGS="${RUSTFLAGS:-} -Clink-arg=-Wl,--build-id=0x$BUILD_ID_TEST_EXPECTED"

len=${#BUILD_ID_TEST_EXPECTED}
export BUILD_ID_LEN=$((len / 2))

exec cargo test --features buildid-section-inject
