//! Shared details of the stamp embedded in WebAssembly linear memory.
//!
//! This module is public so that `buildid-wasm-stamp` and compatible tooling
//! can locate and update the slot. It is not intended as an application API.

/// Name of the conventional WebAssembly build-id custom section.
pub const CUSTOM_SECTION_NAME: &[u8] = b"build_id";

/// Number of bytes in a stamper-generated SHA-256 build ID and the maximum
/// length of a linker-generated build ID that fits in the guest slot.
pub const ID_LEN: usize = 32;

/// Value stored in the guest slot before it has been stamped.
pub const UNSTAMPED_ID: &[u8; ID_LEN] = b"unstamped-buildid-wasm-v1-000000";

/// Slot mode used before the Wasm binary has been stamped.
pub const MODE_UNSTAMPED: u8 = 0xff;

/// Nonzero length marker used before stamping so Wasm optimizers retain the
/// complete contiguous slot in the data segment.
pub const UNSTAMPED_LEN: u8 = 0xff;

/// Slot mode used for a SHA-256 ID generated by `buildid-wasm-stamp`.
pub const MODE_HASH: u8 = 1;

/// Slot mode used when copying the top-level module or component build ID.
pub const MODE_TOP_LEVEL: u8 = 2;

/// Prefix used to unambiguously locate the guest-visible stamp slot.
pub const SLOT_PREFIX: &[u8; 16] = b"buildid-wasm-v1:";

/// Suffix used to unambiguously locate the guest-visible stamp slot.
pub const SLOT_SUFFIX: &[u8; 16] = b":buildid-wasm-v1";
