name: ci
on:
  push:
    branches: 
      - "master"
    tags:
      - "*"
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust_version: [beta]
    env:
      BUILD_ID_LEN: 20
      RUST_LOG: debug 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          components: clippy

      - run: cargo install cargo-hack

      - name: Clippy
        run: cargo hack --feature-powerset clippy -- -D warnings

      - name: Build
        # NOTE: we don't feature-powerset here because we need to provide
        # symbols for some of the specific lookup mechanisms
        # NOTE: we don't build the entire workspace because
        # buildid-linker-symbols does not work on all platforms (for example,
        # it fails on macos)
        run: cargo build --all-targets

      - name: Test
        run: cargo test --all-targets

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check
      - run: cargo clippy --all --all-targets -- -D warnings

  test-specific:
    env:
      RUST_LOG: debug
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust_version: [beta]
        script: [test-gnu-ld, test-gnu-ld-symbol-start-end]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}

      - run: ./scripts/${{ matrix.script }}
