name: ci
on:
  push:
    branches-ignore:
      - '**.tmp'
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust_version: [beta]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - run: cargo install cargo-hack

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: --feature-powerset clippy -- -D warnings

      - name: Build
        # NOTE: we don't feature-powerset here because we need to provide
        # symbols for some of the specific lookup mechanisms
        uses: actions-rs/cargo@v1
        env:
          BUILD_ID_LEN: 20
        with:
          command: build
          args: --all-targets --all

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test-specific:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust_version: [beta]
        script: [test-gnu-ld, test-gnu-ld-section-inject, test-gnu-ld-symbol-start-end]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          profile: minimal

      - uses: Swatinem/rust-cache@v1

      - run: ./scripts/${{ matrix.script }}

